
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fchjeqgwiiacgirwjaze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjaGplcWd3aWlhY2dpcndqYXplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5ODQwMDAsImV4cCI6MjA1MTU2MDAwMH0.7zVgqH_L-K4Kq7dH6rHjFyTi5pWVzWKj1Iqo_xYPwM8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
